version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: system-authorization
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather_network
volumes:
  postgres_data:
networks:
  weather_network:
    driver: bridge
